### ISSUE TITLE
Migrate to new Jakarta namespace

### ISSUE THREAD

**Issue by hantsy** [JavaMoney/jsr354-api#142]
Aligned to Jakarta EE 9, migrate to jakarta namespace.

**Comment by keilw** [comment]
Can you please point out the file where this is really relevant here? I know for sure Moneta and other libraries have it, but here there is not even a POM reference to Jakarta EE, so I will close this and please don't create blanket-issues in every repository for that kind of stuff.

**Comment by DRoppelt** [comment]
I assume they meant the namespace as in the package the files lay in. Is it an issue with they stay in `javax.money`? https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks/ make it sound like trademark issue.

> The javax package namespace may be used within Jakarta EE specifications but may be used “as is” only.  No modification to the javax package namespace is permitted within Jakarta EE component specifications. Jakarta EE specifications that continue to use the javax package namespace must remain TCK compatible with the corresponding Java EE specifications.

I find the whole thing rather confusing, but my takeaway is that jsr354 can only change if it is not within the javax namespace?
