### ISSUE TITLE
Quarkus: Unable to use reflection for javax.money.MonetaryAmount

### ISSUE THREAD

**Issue by timonzi** [JavaMoney/jsr354-api#147]
We have multiple Quarkus applications, which use java money (javax.money:money-api:1.1).
The problem is now, that we get a warning in every application, that says, that the class cannot be registered for reflection.

```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- javax.money.MonetaryAmount (source: SmallRyeOpenApiProcessor > de.wilken.p5.fw.types.api.common.MonetaryAmountType)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

As mentioned in the warning a solution would be an empty beans.xml or the creation of the Jandex index using the jandex-maven-plugin. We could in theory handle this by ourself by adding application properties to this Maven artifact, but then we have to this this in 60+ applications.
Is there any chance, that you add this empty beans.xml, as you probably do not want to add the jandex index (I assume).

**Comment by keilw** [comment]
You'll have to add this in your application, we cannot fix issues with CDI, Spring or any other DI system in our JARs.

**Comment by timonzi** [comment]
> You'll have to add this in your application, we cannot fix issues with CDI, Spring or any other DI system in our JARs.

Sorry, but I have to correct you. I think you want to say that you don't want to fix this - it would be possible. So "cannot" is the wrong term in my opinion. An empty beans.xml would probably not break your code/functionality.

But thank you for the quick response!

**Comment by keilw** [comment]
It is not our responsibility to fix CDI, we could but it is useless to other DI containers like Spring and while you may use an older version of CDI/Quarkus, there are several changes in CDI 4/Lite: https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/CDI-Full-vs-CDI-Lite-What-changed-in-Contexts-and-Dependency-Injection-40 where throwing in an empty beans.xml will affect the discovery, therefore we will not do this.

**Comment by keilw** [comment]
Feel free to ask this in [jakarta-money](https://github.com/JavaMoney/jakarta-money/issues), that is an extension/library for Jakarta EE support. If anywhere I could imagine there, but not in the core API or RI.

**Comment by timonzi** [comment]
Thank you for the explanations! I will check whether they can help me.
