### ISSUE TITLE
getNumberType() return Class<? extends Number>

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-api#78]
See https://github.com/JavaMoney/jsr354-api/pull/52. The PR is likely outdated as such, but the aim should be remembered and applied when it's next possible.

**Comment by msgilligan** [comment]
Actually as I mentioned in #52 and in [JAVAMONEY-154](https://java.net/jira/browse/JAVAMONEY-154), the spec says:

> It explicitly does not constrain the type returned to be a subtype of java.lang.Number to allow alternate implementations to be used.

I think this issue can be closed.

**Comment by keilw** [comment]
Thanks, makes sense, so alternate implementations may use something different.
