### ISSUE TITLE
Java8 vs Java9 difference

### ISSUE THREAD

**Issue by ptahchiev** [JavaMoney/jsr354-api#84]
hello guys, with Java9 this code:
```
MonetaryFormats.getAmountFormat(AmountFormatQueryBuilder.of(Locale.US).set(CurrencyStyle.SYMBOL).set(AmountFormatParams.PATTERN, "¤##.##").build()).format(source);
```
returns €10 and with Java8 returns EUR10.. why is that?

**Comment by ptahchiev** [comment]
Any news on this? It blocks me from updating my project to java9 :(

**Comment by keilw** [comment]
What is the expected behavior?
Using `CurrencyStyle.SYMBOL` I would say that `€10` seems correct. Since the JDK and its currency formatting are used underneath the hood, it is possible that a Java bug or inconsistency was fixed.

**Comment by ptahchiev** [comment]
Hi,
I don't really know what the expected behaviour is. All I could say is that behaviour differs from java8 to java9:
            Locale.US          Any Other Locale (for example UK)
java8    $5                      USD 5
java9    $5                      $5

I construct the `MonetaryAmount` by simply calling `Money.of(5, "USD")`

**Comment by keilw** [comment]
Actually I just ran
```
amt = Money.of(5, "USD");     System.out.println(MonetaryFormats.getAmountFormat(AmountFormatQueryBuilder.of(Locale.US).set(CurrencyStyle.SYMBOL).set(AmountFormatParams.PATTERN, "¤##.##").build()).format(amt));
```

And it prints `$5` on JDK 1.8.0_192. So it works on Java 8. What combination of JDK/JRE and OS did you use?

**Comment by keilw** [comment]
This is really old, does it still occur?

**Comment by keilw** [comment]
Looks like there is no difference between Java 8 and 9+ now.
