### ISSUE TITLE
module-info in JAR breaks Android build tools

### ISSUE THREAD

**Issue by msgilligan** [JavaMoney/jsr354-api#85]
So, I finally upgraded my Android libraries and projects to use the Java 8 version of Java Money, rather than the Backport (now that Android 7+ has 36% of the market and growing.) I discovered that version 1.0.3 (`javax.money:money-api:1.0.3`) breaks the Android "desugaring" tool. Resulting in the message:

    java.lang.IllegalArgumentException: Type without superclass: module-info

Google has a fix for this in their recent "Canary" builds, starting with [Android Studio 3.3 Canary 1](https://androidstudio.googleblog.com/2018/06/android-studio-33-canary-1-available.html)

My recommendation is not to make any changes to the JavaMoney API JAR, but to recommend that developers either stick with version 1.0.1 or build with the pre-release Android tools.

**Comment by msgilligan** [comment]
We could probably close this issue and add it to the README or some place in the documentation.

**Comment by keilw** [comment]
Would you propose a PR for the README so it can be provided for 1.0.4? Even if you are not Associate Member right now, the README sounds less critical than actual code changes.

**Comment by msgilligan** [comment]
Sure. Assign it to me, please.

**Comment by msgilligan** [comment]
When do you plan on releasing 1.0.4? I started on the path of writing something for the README and then thought I should test the configuration before recommending it. I discovered that the JDK8 JavaMoney

**Comment by keilw** [comment]
Probably a bit sooner than a 1.4 RI (which would be based on that) but on average we had more or less a quarterly release cycle for Moneta (it seems fashionable nowadays to release often ;-) So maybe later this quarter, I already fixed the OSGi signature but there are still a few open issues in https://github.com/JavaMoney/jsr354-api/milestone/1. https://github.com/JavaMoney/jsr354-api/issues/84 could be RI related, so it may get transferred if confirmed.

**Comment by msgilligan** [comment]
We should try to set up an Android build on Travis (if there isn't already)
