### ISSUE TITLE
Wrong Javadoc in MonetaryOperator

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-api#88]
The Javadoc of `javax.money.MonetaryOperator` says

> This interface extends {@code java.util.function.UnaryOperator} introduced by Java 8.

but it does not extend `java.util.function.UnaryOperator`

**Comment by stokito** [comment]
But why it's not implements the UnaryOperator? Maybe this was just missed so we should implement it instead of removing the comment.

**Comment by keilw** [comment]
It's certainly not supposed to extend `UnaryOperator`, was also fixed with #109 and not closed.
